### PR TITLE
Add content and design of works and aboutme sections  to my portfolio

### PR DESCRIPTION
**Pull request by khitermedachraf**
I added the HTML content of all card projects/skills, I also used the Grid layout for the cards container. Then I used the flexbox for styling the content of each project/skill placeholder (flexbox-column and flexbox-row). 
other than that I completed the design of links/ buttons/text/png using pure CSS.

### CODE REVIEW

**Review by Kingstalux — COMMENTED** [review]
Hi @khitermedachraf , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f644550476b6e5269456e6965632f67697068792e676966

## Invalid Code Review Request 🛑 

- [ ] You have submitted a project that has failed linters checks. Kindly fix your linters and make sure they are passing before requesting for a review as your project cannot be reviewed if your linters are not passing 😄 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by khitermedachraf** [comment]
Ahh okay, thank you @Kingstalux.
 I didn't know about this rule before.
I did resubmit it by mistake for a second time, I hope it will not be counted in my 3 attempts

**Review by phelian23 — CHANGES_REQUESTED** [review]
Hi @khitermedachraf, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that is failing linter checks. Kindly fix it and ask for a review when you are ready.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **Does not count** into the code reviews limit._

**Comment by khitermedachraf** [comment]
I'm sorry My code reviewers for making a lot of commits about WebHint fixing errors
because the npx hint validator doesn't work on my gitBash after searching and a lot of effort, I found that it is a bug reported in 2019.
This is the my issue: [WebHint Bug](https://github.com/webhintio/hint/issues/3134)

**Pull request closed without merging**
